# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "611fdf6f2d36ff8381a8beb94bcabb92"
name = "game-over-new"
handle = "game-over-new"
application_url = "https://uzbekistan-vip-district-r.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "new-apps-dev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://uzbekistan-vip-district-r.trycloudflare.com/auth/callback",
  "https://uzbekistan-vip-district-r.trycloudflare.com/auth/shopify/callback",
  "https://uzbekistan-vip-district-r.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
